Vagrant.configure("2") do |config|
  # more powah
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "3"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end  

  # install custom build packages which would probably not be available in repos yet
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive;test -d /vagrant/bootstrap-packages && ls /vagrant/bootstrap-packages/*.deb|xargs dpkg -i || true"

  # make it zsh
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive;apt-get -yqq install zsh; chsh -s /usr/bin/zsh vagrant; chsh -s /usr/bin/zsh root"
  config.vm.provision "file", source: "~/.zshrc.vagrant", destination: "/home/vagrant/.zshrc"
  config.vm.provision "file", source: "~/.zshrc.vagrant", destination: "/root/.zshrc"
  config.ssh.host = "localhost"

  # add dotfiles
  rsync_args = ["--verbose", "--archive", "--delete", "-z", "--include=.zl*", "--include=.zp**", "--include=.zshenv", "--include=.vim**", "--exclude=*"]
  config.vm.synced_folder "/Users/johanbloemberg/", "/home/vagrant/", type: "rsync", rsync__args: rsync_args
  config.vm.synced_folder "/Users/johanbloemberg/", "/root/", type: "rsync", rsync__args: rsync_args

end


