Vagrant.configure("2") do |config|
  # make it zsh
  config.vm.provision "shell", inline: "
  DEBIAN_FRONTEND=noninteractive;apt-get -yqq install zsh git;
  chsh -s /usr/bin/zsh vagrant; chsh -s /usr/bin/zsh root
  "

  config.ssh.host = "localhost"

  # add dotfiles
  rsync_args = ["--verbose", "--archive", "--delete", "-z"]
  config.vm.synced_folder "~/.dotfiles/", "/home/vagrant/.dotfiles/", type: "rsync", rsync__args: rsync_args
  config.vm.synced_folder "~/.dotfiles/", "/root/.dotfiles/", type: "rsync", rsync__args: rsync_args

  # install and apply rcm
  config.vm.provision "shell", inline: "
  wget -q https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb -O /tmp/rcm_1.2.3-1_all.deb
  sudo dpkg -i /tmp/rcm_1.2.3-1_all.deb
  rcup -f -tag vagrant
  sudo -u vagrant rcup -f -tag vagrant
  "
end

Vagrant.configure("2") do |config|
  # more powah
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "3"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # install custom build packages which would probably not be available in repos yet
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive;test -d /vagrant/bootstrap-packages && ls /vagrant/bootstrap-packages/*.deb|xargs dpkg -i || true"
end
